package sqldblogger

const (
	MessageCommit              = "Commit"
	MessageRollback            = "Rollback"
	MessageResultLastInsertId  = "ResultLastInsertId"
	MessageResultRowsAffected  = "ResultRowsAffected"
	MessageBegin               = "Begin"
	MessagePrepare             = "Prepare"
	MessageClose               = "Close"
	MessageBeginTx             = "BeginTx"
	MessagePrepareContext      = "PrepareContext"
	MessagePing                = "Ping"
	MessageExec                = "Exec"
	MessageExecContext         = "ExecContext"
	MessageQuery               = "Query"
	MessageQueryContext        = "QueryContext"
	MessageResetSession        = "ResetSession"
	MessageCheckNamedValue     = "CheckNamedValue"
	MessageRowsClose           = "RowsClose"
	MessageRowsNext            = "RowsNext"
	MessageRowsNextResultSet   = "RowsNextResultSet"
	MessageStmtClose           = "StmtClose"
	MessageStmtExec            = "StmtExec"
	MessageStmtQuery           = "StmtQuery"
	MessageStmtCheckNamedValue = "StmtCheckNamedValue"
	MessageStmtQueryContext    = "StmtQueryContext"
	MessageStmtExecContext     = "StmtExecContext"
)
