name: Reports
on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, synchronize, reopened ]
permissions:
  contents: read
jobs:
  reports:
    name: Test and Report
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.21', '1.20', '1.19', '1.18', '1.17' ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54.2
      - name: Run Unit Tests
        run: ./test.sh
      - name: Send coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: coverage.out
          flag-name: Go-${{ matrix.go }}
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}